# gui_layout.kv

<DashboardScreen>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            MDLabel:
                text: 'Dashboard'
                halign: 'center'
            MDLabel:
                text: 'Dashboard'
                halign: 'center'
            MDLabel:
                text: 'Dashboard'
                halign: 'center'

        MDLabel:
            text: 'Dashboard2'

        MDRaisedButton:
            text: 'Zu Einstellungen'
            size_hint: (1,1)

            pos_hint: {'center_x': 0.5, 'center_y': 1}

            on_release: app.root.current = 'settings'

<SettingsScreen>:
    BoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: 'Einstellungen'
        MDRaisedButton:
            text: 'Zurück zum Dashboard'
            on_release: app.root.current = 'dashboard'


# Füge ähnliche Layouts für die anderen Bildschirme hinzu
