name: Build Linux DEB Package with Release

on: 
  workflow_dispatch:

permissions: # Explicitly setting permissions
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Read Version
      id: get_version
      run: |
        version=$(cat VERSION)
        echo "::set-output name=version::$version"
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential fakeroot dpkg-dev
        pip install nuitka PySide6 base58==2.1.1 cryptography==3.4.8 mnemonic==0.21 PySide6==6.6.1 PySide6_Addons==6.6.1 PySide6_Essentials==6.6.1 shiboken6==6.6.1

    - name: Compile with Nuitka
      run: |
        python -m nuitka --follow-imports --include-module=mnemonic --enable-plugin=pyside6 --standalone --output-dir=./build --output-filename=eMinuto main_qt.py

    - name: Create DEB Package
      run: |
        mkdir -p build/deb/usr/local/bin
        cp build/eMinuto.dist/eMinuto build/deb/usr/local/bin/
        mkdir -p build/deb/DEBIAN
        echo "Package: eminuto" > build/deb/DEBIAN/control
        echo "Version: $VERSION" >> build/deb/DEBIAN/control
        echo "Section: base" >> build/deb/DEBIAN/control
        echo "Priority: optional" >> build/deb/DEBIAN/control
        echo "Architecture: amd64" >> build/deb/DEBIAN/control
        echo "Depends: python3, python3-pyside6" >> build/deb/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> build/deb/DEBIAN/control
        echo "Description: eMinuto Desktop Application" >> build/deb/DEBIAN/control
        dpkg-deb --build build/deb build/eMinuto-${VERSION}.deb

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/eMinuto-${VERSION}.deb
        asset_name: eMinuto-${VERSION}.deb
        asset_content_type: application/vnd.debian.binary-package
