name: Create XPI and Release

on:
  push:
    tags:
      - 'v*'   # Startet den Workflow bei neuen Versionstags
  workflow_dispatch:  # Ermöglicht das manuelle Starten des Workflows

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Extract version from manifest.json
      id: get_version
      run: |
        VERSION=$(grep '"version"' src/manifest.json | sed -E 's/.*"version": "([^"]+)".*/\1/')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Build XPI
      run: |
        mkdir -p build/PrioMailbox
        rsync -av --exclude="assets" --exclude=".*" --exclude="*.sh" ./src/ build/PrioMailbox/
        sed -i 's/"name": "[^"]*"/"name": "PrioMailbox"/' build/PrioMailbox/manifest.json
        cd build/PrioMailbox
        zip -r ../PrioMailbox_v${VERSION}.xpi . -x ".*" "*.sh" "assets/*"
        cd ../..

    - name: Debug - List build directory contents
      run: |
        echo "Contents of build directory:"
        ls -l ./build
        echo "Contents of PrioMailbox directory:"
        ls -l ./build/PrioMailbox

    - name: Verify XPI File
      run: |
        if [ ! -f "./build/PrioMailbox_v${VERSION}.xpi" ]; then
          echo "XPI file not found!"
          exit 1
        else
          echo "XPI file found at ./build/PrioMailbox_v${VERSION}.xpi"
        fi

    - name: Check if release exists
      id: check_release
      uses: actions/github-script@v6
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const release = releases.data.find(release => release.tag_name === `v${process.env.VERSION}`);
          if (release) {
            core.setOutput('release_id', release.id);
            core.setOutput('upload_url', release.upload_url);
          } else {
            core.setOutput('release_id', '');
            core.setOutput('upload_url', '');
          }

    - name: Debug - Check Release Outputs
      run: |
        echo "Release ID: ${{ steps.check_release.outputs.release_id }}"
        echo "Upload URL: ${{ steps.check_release.outputs.upload_url }}"

    - name: Create Release
      if: ${{ steps.check_release.outputs.release_id == '' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: "PrioMailbox v${{ env.VERSION }}"
        draft: false
        prerelease: false

    - name: Debug - New Release Outputs
      if: ${{ steps.check_release.outputs.release_id == '' }}
      run: |
        echo "New release created."
        echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"

    - name: Set Upload URL for New Release
      if: ${{ steps.check_release.outputs.release_id == '' }}
      run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

    - name: Set Upload URL for Existing Release
      if: ${{ steps.check_release.outputs.release_id != '' }}
      run: echo "UPLOAD_URL=${{ steps.check_release.outputs.upload_url }}" >> $GITHUB_ENV

    - name: Upload XPI to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: ./build/PrioMailbox_v${{ env.VERSION }}.xpi
        asset_name: PrioMailbox_v${{ env.VERSION }}.xpi
        asset_content_type: application/x-xpinstall
