name: Build Windows with Release

on: 
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get version from file
      run: |
        $version = Get-Content -Path VERSION -Raw
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka PySide6 base58==2.1.1 cryptography==3.4.8 mnemonic==0.21 PySide6==6.6.1 PySide6_Addons==6.6.1 PySide6_Essentials==6.6.1 shiboken6==6.6.1

    - name: Compile with Nuitka
      run: |
        python.exe -m nuitka --follow-imports --include-module=mnemonic --enable-plugin=pyside6 --include-data-dir=./src/gui/qt/translation=src/gui/qt/translation --disable-console --standalone --output-dir=./build --output-filename=eMinuto.exe main_qt.py --assume-yes-for-downloads

    - name: Rename and Zip Output
      run: |
        Move-Item ./build/main_qt.dist ./build/eMinuto
        Compress-Archive -Path ./build/eMinuto/* -DestinationPath ./build/eMinuto-${{ env.VERSION }}-windows.zip
      shell: pwsh

    - name: Check if release exists
      id: check_release
      uses: actions/github-script@v6
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const release = releases.data.find(release => release.tag_name === `v${process.env.VERSION}`);
          if (release) {
            core.setOutput('release_id', release.id);
            core.setOutput('upload_url', release.upload_url);
          } else {
            core.setOutput('release_id', '');
            core.setOutput('upload_url', '');
          }

    - name: Create Release
      if: ${{ steps.check_release.outputs.release_id == '' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: eMinuto v${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: ${{ steps.check_release.outputs.release_id != '' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.check_release.outputs.upload_url }}
        asset_path: ./build/eMinuto-${{ env.VERSION }}-windows.zip
        asset_name: eMinuto-${{ env.VERSION }}-windows.zip
        asset_content_type: application/zip